apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169663902
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169663902
    app.kubernetes.io/part-of: test-app-169663902
  name: java-quarkus-169663902
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169663902
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169663902
    spec:
      containers:
      - image: quay.io/hacdev/1v5bvl6p-tenant/test-app-169663902/java-quarkus-169663902@sha256:15119a46f9dd48ed9312b1bf80665043375e6b13e100828f541236e746b66b58
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
